const browserGlobals = {
  CSS: 'readonly',
  URLSearchParams: 'readonly',
  clearTimeout: 'readonly',
  console: 'readonly',
  document: 'readonly',
  fetch: 'readonly',
  HTMLElement: 'readonly',
  localStorage: 'readonly',
  location: 'readonly',
  navigator: 'readonly',
  sessionStorage: 'readonly',
  setTimeout: 'readonly',
  window: 'readonly',
};

const taskTrackerGlobals = {
  API_URL: 'readonly',
  callAPI: 'readonly',
  cacheClear: 'readonly',
  cacheGet: 'readonly',
  cachedFetch: 'readonly',
  currentView: 'readonly',
  confirmDelete: 'readonly',
  dashboardV2Can: 'readonly',
  dashboardV2TableFilterMatches: 'readonly',
  escapeAttr: 'readonly',
  escapeHtml: 'readonly',
  focusNavigationRecord: 'readonly',
  getAll: 'readonly',
  getDashboard: 'readonly',
  getCompanyName: 'readonly',
  handleSessionExpired: 'readonly',
  idToken: 'writable',
  logTaskTime: 'readonly',
  navigateTo: 'readonly',
  openAddModal: 'readonly',
  openEditModal: 'readonly',
  queueOfflineWrite: 'readonly',
  showToast: 'readonly',
  showPRModal: 'readonly',
  showVendorModal: 'readonly',
  t: 'readonly',
  tableData: 'readonly',
  _allPRs: 'readonly',
  _allVendors: 'readonly',
};

export default [
  {
    ignores: ['dist/**', 'node_modules/**', '.claude/worktrees/**'],
  },
  {
    files: ['frontend/ai-chat.js', 'frontend/api.js', 'frontend/mobile-nav.js', 'frontend/mobile-v3.js', 'frontend/notifications.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: { ...browserGlobals, ...taskTrackerGlobals },
    },
    rules: {
      'no-constant-condition': 'error',
      'no-dupe-args': 'error',
      'no-func-assign': 'error',
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_$' }],
      'no-useless-catch': 'error',
    },
  },
  {
    files: ['build.mjs', 'playwright.config.js', 'tests/**/*.js', 'tests/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...browserGlobals,
        Buffer: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
        console: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
      },
    },
    rules: {
      'no-dupe-args': 'error',
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
];
